# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6ee19b7d984fc35ddc7d70af179c0fb5b5b8f8672d8a4b858e27a155e26aaa6297b53e942c731ca13c071f0884fdf5fb6e1e0ef28cd2498a49816a77d8d837a

test:
  secret_key_base: 0746404a995aab7ba48b70c1247ad4fb09a1e16b8606fa405c8bdfe3aa856fd09aca7f8dbd0f2406e64c222594b930d46915a65998e656ccd0de4ccb75bc41ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
